name: CI CD Eimport Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Change PHP Version to 8.2
        run: sudo update-alternatives --set php /usr/bin/php8.2

      - name: Deploy To Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo update-alternatives --set php /usr/bin/php8.2
            cd /home/satwagiadev-eimport/htdocs/eimport.satwagiadev.site
            git pull origin main
            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan route:cache
            php artisan view:cache
            php artisan config:cache
            php artisan config:clear
